language: ruby
sudo: false
cache: bundler
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  email:
    on_success: never
    on_failure: change

script: 
  - make build
  - make check


addons:
  apt:
    packages:
    - libcurl4-openssl-dev

before_deploy:
  - mkdir ./docs
  - cp -r ./_site ./docs 
	- touch ./docs/.nojekyll
  on:
    tags: true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES_DEPLOY  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: ./docs
  on:
    tags: true
