language: ruby
os: linux
dist: xenial
cache: bundler

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  email:
    on_success: never
    on_failure: change

script: 
  - make build
  - make check


addons:
  apt:
    packages:
    - libcurl4-openssl-dev

before_deploy:
  - mkdir ./docs
  - cp -r ./_site ./docs
  - touch ./docs/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_PAGES_DEPLOY  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: ./docs
  strategy: git
  on:
    tags: true
