language: ruby
sudo: false
cache: bundler
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
 - make config

# Overwrite install to prevent travis from running bundler
# (so that gems get installed into normal location. This
# allos 'sass' to be used on command line)
install:
  - ls # No op

script: 
  - make config
  - make build
  - make check

addons:
  apt:
    packages:
    - libcurl4-openssl-dev