
title: Adam St. Amand
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Social link
github_url:  https://github.com/adam-stamand  # add url link
stack-overflow_url: https://stackoverflow.com/users/3029052  # add url link
linkedin_url: https://www.linkedin.com/in/adam-st-amand/ # add url link
angellist_url: https://angel.co/adam-stamand # add url link

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-octicons
  - jemoji
  - jekyll-github-metadata


collections:
  interests:
    output: true

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name


include: [_pages]
exclude: [vendor, gemfiles/vendor]